<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Household;
use App\Models\Family;
use App\Models\Resident;
use Illuminate\Support\Facades\Hash;

class HierarchicalDataSeeder extends Seeder
{
    /**
     * Seed the database with Household → Family → Resident hierarchy
     * This creates realistic test data for the Master Collections system
     */
    public function run(): void
    {
        $barangays = config('barangays.list', []);
        $barangayNames = array_keys($barangays);
        
        $hhnCounter = 1; // Global counter for unique HHN numbers
        
        // Create 10 Households across different barangays
        foreach (range(1, 10) as $index) {
            $barangay = $barangayNames[array_rand($barangayNames)];
            $barangayCode = $barangays[$barangay];
            
            $household = Household::create([
                'household_number' => 'HN-2026-' . str_pad($index, 3, '0', STR_PAD_LEFT),
                'house_number' => rand(1, 500),
                'street' => ['Main Street', 'Church Street', 'Market Road', 'Riverside Drive'][array_rand(['Main Street', 'Church Street', 'Market Road', 'Riverside Drive'])],
                'purok' => 'Purok ' . rand(1, 7),
                'barangay' => $barangay,
                'municipality' => 'Buguey',
                'province' => 'Cagayan',
                'full_address' => null, // Will be auto-generated by model
            ]);

            // Create 2-3 families per household
            $familyCount = rand(2, 3);
            foreach (range(1, $familyCount) as $familyIndex) {
                $surnames = ['Dela Cruz', 'Santos', 'Reyes', 'Garcia', 'Rodriguez', 'Martinez', 'Fernandez', 'Lopez', 'Gonzales', 'Perez'];
                $surname = $surnames[array_rand($surnames)];
                
                $family = Family::create([
                    'household_id' => $household->id,
                    'hhn_number' => 'HHN-' . str_pad($hhnCounter++, 3, '0', STR_PAD_LEFT),
                    'head_surname' => $surname,
                    'household_head_id' => null, // Will set after creating head resident
                ]);

                // Create family members
                $memberCount = rand(3, 6);
                $familyHead = null;
                
                foreach (range(1, $memberCount) as $memberIndex) {
                    $firstName = ['Juan', 'Maria', 'Pedro', 'Ana', 'Jose', 'Rosa', 'Miguel', 'Carmen', 'Luis', 'Elena'][array_rand(['Juan', 'Maria', 'Pedro', 'Ana', 'Jose', 'Rosa', 'Miguel', 'Carmen', 'Luis', 'Elena'])];
                    $relationships = ['Household Head', 'Spouse', 'Child', 'Parent', 'Sibling'];
                    
                    $isAutoLinked = ($memberIndex > 2) && (rand(0, 1)); // Last members have 50% chance to be auto-linked
                    
                    $resident = Resident::create([
                        'first_name' => $firstName,
                        'last_name' => $surname,
                        'middle_name' => chr(rand(65, 90)),
                        'email' => strtolower($firstName . '.' . $surname . rand(100, 999) . '@test.com'),
                        'password' => 'password', // Model auto-hashes via 'hashed' cast
                        'date_of_birth' => now()->subYears(rand(18, 65))->format('Y-m-d'),
                        'place_of_birth' => $barangay,
                        'gender' => ['Male', 'Female'][array_rand(['Male', 'Female'])],
                        'civil_status' => ['Single', 'Married', 'Widowed'][array_rand(['Single', 'Married', 'Widowed'])],
                        'purok' => $household->purok,
                        'barangay' => $barangay,
                        'barangay_code' => $barangayCode,
                        'municipality' => 'Buguey',
                        'province' => 'Cagayan',
                        'postal_code' => '3511',
                        'contact_number' => '09' . rand(100000000, 999999999),
                        'household_relationship' => ($memberIndex === 1) ? 'Household Head' : $relationships[array_rand($relationships)],
                        'household_id' => $household->id,
                        'family_id' => $family->id,
                        'is_auto_linked' => $isAutoLinked,
                        'role' => 'citizen',
                        'is_verified' => !$isAutoLinked, // Auto-linked residents are not verified yet
                        'email_verified_at' => now(),
                    ]);

                    // First member is the family head
                    if ($memberIndex === 1) {
                        $familyHead = $resident;
                        $family->update([
                            'household_head_id' => $resident->id,
                        ]);
                    }
                }
            }
        }

        $this->command->info('✅ Created:');
        $this->command->info('   - ' . Household::count() . ' Households');
        $this->command->info('   - ' . Family::count() . ' Families');
        $this->command->info('   - ' . Resident::where('household_id', '!=', null)->count() . ' linked Residents');
        $this->command->info('   - ' . Resident::where('is_auto_linked', true)->count() . ' Auto-linked residents');
    }
}
